# Set up some variables to minimize annoyance
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'
    CADDY_VERSION = '2.7.4'

# Download and untar Caddy
[phases.caddy]
    dependsOn = ['setup']
    cmds = [
        'curl -fsSLo caddy.tar.gz "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_linux_amd64.tar.gz"',
        'tar -zxvf caddy.tar.gz caddy',
        'chmod +x caddy'
    ]

# Format the Caddyfile with fmt
[phases.fmt]
    dependsOn = ['caddy']
    cmds = ['caddy fmt --overwrite Caddyfile']

# Build the React app
[phases.build]
    run = "npm install && npm run build"

# Copy Caddy and build artifacts to a new image and start the Caddy web server
[start]
    runImage = 'ubuntu:20.04'
    onlyIncludeFiles = ['caddy', 'Caddyfile', 'build'] # Use the 'build' folder instead of 'dist'
    cmd = './caddy run --config Caddyfile --adapter caddyfile 2>&1'
